Repository ProjectTorreyPines/FUSE.jl, pull requests merged in 2025-03, with the labels that each got.

#823 Optional reuse Green function table in ActorFRESCO
  src/actors/equilibrium/fresco_actor.jl
Labels: enhancement, performance

#841 Prevent infinite control-point weights
  src/actors/pf/pf_active_actor.jl
Labels: bug

#828 Improved simple beam model
  src/actors/hcd/nbi/nb_simple_actor.jl
  src/cases/CAT.jl
  src/cases/D3D.jl
  src/cases/DTT.jl
  src/cases/HDB5.jl
  src/cases/ITER.jl
  src/ddinit/init_hcd.jl
  src/parameters/parameters_inits.jl
Labels: ready for review

#837 Fix bugs in Ip control
  src/actors/control/ip_control.jl
Labels: bug, control
