Repository ProjectTorreyPines/FUSE.jl, pull requests merged in 2025-09, with the labels that each got.

#977 Setup default flux-matching algorithm by TGLF model
  src/actors/transport/flux_matcher_actor.jl
Labels: enhancement

#987 Fix FluxControlPoint vector type and Base.Dict extension
  src/actors/equilibrium/chease_actor.jl
  src/actors/equilibrium/tequila_actor.jl
  src/utils_end.jl
Labels: bug, minor

#984 Need to use somega to run OMFIT now
  src/cases/D3D.jl
Labels: cases

#993 Add Google form signup link
  README.md
  docs/src/cases_docs.jl
Labels: documentation
