Repository ProjectTorreyPines/FUSE.jl, pull requests merged in 2025-06, with the labels that each got.

#918 Deployment scripts for NERSC Perlmutter
  deploy/perlmutter/base.lua
  deploy/perlmutter/deploy.sh
  deploy/perlmutter/install_fuse_environment.jl
Labels: work in progress, deployment

#902 Restore qed_init_from_imas to work on dd alone
  src/actors/current/qed_actor.jl
Labels: compatibility

#927 Update Perlmutter deployment
  deploy/perlmutter/base.lua
  deploy/perlmutter/deploy.sh
  deploy/perlmutter/install_fuse_environment.jl
Labels: deployment

#917 Pedestal analytic
  src/FUSE.jl
  src/actors/pedestal/AnalyticPedestal_actor.jl
  src/actors/pedestal/pedestal_actor.jl
Labels: ready for review
